image: node:20

pages:
  stage: deploy
  script:
    - npm ci
    - npm test
    - npm run build
    - rm -rf public && mv dist public
  artifacts:
    paths:
      - public
  variables:
    VITE_NOTIFY_URL: $VITE_NOTIFY_URL
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
