export const STORY = [
  "No me imaginaba que se podía querer tanto a alguien en tan poco tiempo, no concebía que iba a conocer a un ser tan espectacular que rompiera todos mis paradigmas sobre el amor que vivían tatuados en mí, no me esperaba lo mucho que sentiría tu ausencia una vez que decidieras que lo nuestro no iba a funcionar...",
  "No quiero que el paso del tiempo nuble todo lo que sentí por ti y sé que sentiste por mí, ese primer beso en el lugar menos romántico del mundo que me hizo sentir como si tú fueras todo mi universo y todo lo demás no importara, ese pensamiento de que ya no podía esperar más y tenía que descubrir el sabor de tus labios...",
  "Esa emoción al darme cuenta de que todos los rumores eran ciertos y besabas mejor que la propia diosa del amor, esa sensación cuando me sonreías después de una sesión romántica de beso tras beso, ese sentimiento cuando te veía a lo lejos antes de iniciar una cita y cómo te veía como la mujer más hermosa del mundo...",
  "Cómo sentía tu calor cuando nos abrazábamos viendo lo hermoso del museo Anahuacalli, esas pláticas profundas en las cafeterías que me permitían descubrir un poquito más de la persona que tanto me había fascinado, esas salidas a museos, el poder abrazarte mientras veíamos una película o dormíamos...",
  "Cuando me explicabas conceptos económicos o me hablabas sobre la flora de los lugares a donde íbamos, lo fácil que se sentía abrirme contigo y decirte pensamientos o sentimientos que nunca había compartido con nadie...",
  "Esa confianza de compartirme esos gustos que te avergonzarían si el gran público los supiera, la serotonina que me daba el ver un nuevo mensaje tuyo en mi celular y saber que aunque lejos seguías ahí para mí, todo eso y más estoy extrañando de ti...",
  "No lo voy a negar, no soy tan estoico como para aceptar que todo ya acabó y guardo en mi corazón la esperanza de que como una vez lo hiciste cambies de opinión una vez más, tengo fe de que me extrañes solo una fracción de lo que te estoy extrañando en este momento...",
  "Hay conexiones que simplemente no se pueden dejar ir así de fácil, por lo que esta es mi manera de hacerte saber lo que estoy sintiendo. Si tú estás feliz y te sientes plena con tu decisión, no puedo ser tan egoísta para pedirte que la reviertas...",
  "Pero si algo en ti está dudando o no se siente feliz con este estatus quo, hazle caso. La vida es muy corta como para negarse a sentir...",
  "De todas formas, no quería que nuestra última date haya acabado con un error tan tonto como el que cometí el pasado viernes, y no quiero que me quites tantos puntos en mi encuesta de satisfacción final… por lo que te debo una mejor última cita...",
]
